name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pull the project
        run: git pull

      - name: Create the .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          DATABASE_URL: "mongodb+srv://Agoulexher:JneU9cWAoNfcZtGB@prod.quwntjf.mongodb.net/prod?retryWrites=true&w=majority"
          NODE_ENV: "production"

      - name: Build the project
        run: npm run build

      - name: Check pm2 version
        run: pm2 -V

      - name: Restart pm2
        run: pm2 restart chatnow-node
