name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pull the project
        run: git pull

      - name: Build the project
        run: npm run build

      - name: Add pm2 to PATH
        run: echo "::add-path::/root/.nvm/versions/node/v14.17.6/bin/"

      - name: Restart pm2
        run: pm2 restart chatnow-node
